# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-22 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_buddy', '0003_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='joined_by',
            field=models.ManyToManyField(related_name='joins', to='travel_buddy.User'),
        ),
    ]
